### ISSUE TITLE
[BUG] Config parser - Inconsistent and unexpected "Missing equal sign" error

### ISSUE THREAD

**Issue by Coryf88** [SQFvm/runtime#126]
**Describe the bug**
The config parser inconsistently throws an unexpected "Missing equal sign" error for classes.

**To Reproduce**
1. Execute `configparse__ "class A {};"` a few times.
2. See error: [ERR] [L1|C12|file]   Missing equal sign (`=`).
The error's column is also inconsistent. I've seen 12, 13, 14, 15, 19 and 20.

**Expected behavior**
No error.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by X39** [comment]
cannot reproduce
