### ISSUE TITLE
[BUG] Unknown preprocessor directive error when selecting element from array

### ISSUE THREAD

**Issue by Zarickan** [SQFvm/runtime#136]
**Describe the bug**
sqfvm seems to treat the `#alpha` as a preprocessor directive, instead of the array select operator when it is the first thing on the line.

**To Reproduce**
Run the following code in sqfvm:
```sqf
alpha = 2;
array = [1, 2, 3, 4, 5];
array
#alpha;
```

**Expected behavior**
Expecting code to return 3.

**Screenshots**
[sqfvm output](https://i.imgur.com/ldeSQdh.png), [output from arma](https://i.imgur.com/Y4LPamv.png)

**Comment by X39** [comment]
Developer console is, Unlike the input of sqf-vm, not preprocessed. Could you double check the behavior with the actual ingame preprocessor using `Compile preprocessfile`

**Comment by Zarickan** [comment]
You are right.

If I put the code in a file and do `compile (preprocess "test.sqf")`, I just get an empty string back. If I try and run it with execVM arma erors with "Preprocessor failed with error - Invalid file name(empty filename)".

I can read the file using `loadFile "test.sqf"` without issue.

It seems that the preprocessor treats any line where the first non whitespace character is a # as a preprocessor directive.
