### ISSUE TITLE
[BUG] Executing 1+1 assembly causes `back() called on empty vector`

### ISSUE THREAD

**Issue by overfl0** [SQFvm/runtime#167]
Assembly:
```assembly
push 1
push 1
callbinary +
```

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: ####\SQFvm\Debug\libcsqfvm.dll
File: #######\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\vector
Line: 1556

Expression: back() called on empty vector

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------

**Comment by X39** [comment]
```cpp
1:	 _fnc = fromassembly__ ["push 1", "push 1", "callbinary +"];
2:	call _fnc
3:	
```
Not reproducible
