### ISSUE TITLE
[BUG] Null config causes fatal error on config commands

### ISSUE THREAD

**Issue by PabstMirror** [SQFvm/runtime#178]
**Describe the bug**
 Null config causes fatal error on config commands (`isClass`, `isText`, `getNumber` ...)

**To Reproduce**
` .\sqfvm.exe --automated --sqf "isClass configNull;"`
```
Executing...
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[ERR] [L1|C0|__commandline]     Provided value is null.
[FAT] [L1|C0|__commandline]     Stacktrace:<  1 of 1> [L1|C0|__commandline]     [missionNamespace] [SCOPENAME-EMPTY]
isClass configNull;
^^^^^^^
```

**Expected behavior**
- `isClass configNull` - Expected: `false`, gives fatal error
- `getNumber configNull` - Expected: `0`, gives fatal error
- `getText (configFile >> "doesNotExist")` - Expected `""`, gives fatal error
- `isNull configNull` - Expected: `true`, this **does** work correctly!

**Comment by X39** [comment]
Is the expected behavior cross-checked with arma?

**Comment by PabstMirror** [comment]
![image](https://user-images.githubusercontent.com/9376747/128424972-bed2c2c4-c07f-4270-ab50-e3ca189b5459.png)
