### ISSUE TITLE
[BUG] configClasses returns properties

### ISSUE THREAD

**Issue by Coryf88** [SQFvm/runtime#182]
**Describe the bug**
`configClasses` also returns non-class config entries.

**To Reproduce**
1. Execute `sqfvm.exe --automated --config "class Test { property = 0; class TestSub { subProperty = 0; }; };" --sqf """true"" configClasses (configFile >> ""Test"")"`
2. Notice `[INF] Context droped with return value '[property,TestSub]'.`

**Expected behavior**
`[INF] Context droped with return value '[TestSub]'.`

**Screenshots**
N/A

**Additional context**
N/A

**Comment by X39** [comment]
Should be fixed in https://github.com/SQFvm/runtime/commit/d0ae93eb2639fb88c7dbe471edd48239d849b1db

Please reopen if still affected with [latest development release](https://github.com/SQFvm/runtime/actions/runs/5764179067)
