### ISSUE TITLE
Simplify calling of SQF code from the CLI

### ISSUE THREAD

**Issue by overfl0** [SQFvm/runtime#204]
People seem to expect sqfvm to run like other code interpreters, like python, ruby or nodejs - just call `python hello_world.py` and this will execute the code present in that file.

Would it be possible to have such a functionality with sqfvm?

**Comment by X39** [comment]
Pretty much is just a cli thing
So yes, possible

**Comment by danielgran** [comment]
+1

**Comment by X39** [comment]
Implemented in development branch
