### ISSUE TITLE
[BUG] Config parser doesn't support external base classes

### ISSUE THREAD

**Issue by Coryf88** [SQFvm/runtime#92]
**Describe the bug**
Config parser doesn't support [external base classes](https://community.bistudio.com/wiki/Class_Inheritance#External_base_classes).

**To Reproduce**
1. Create a file named `config.cpp`, containing:
```cpp
class externalBaseClass;
class myClass: externalBaseClass {};
```
2. Execute `sqfvm.exe -a --parse-only --input-config config.cpp`
3. See error

**Expected behavior**
No error when using external base classes.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by X39** [comment]
While not a "Known Issue" this is kinda to be expected.

The config parser is a very basic implementation of the Arma Config Parser, as this is not the main focus of SQF-VM.
At some point in the future, it requires a rewrite which then will enable more complex situations. The above however, i am not even sure if it would work in Arma itself.

SQF-VM has no config loaded per default, thus refering to a non-existing config entry would yield and error anyways.

Thanks for your report though. If this is a mandatory requirement for you, i will try to finish this by end of this year

**Comment by Coryf88** [comment]
![20191223151328_1](https://user-images.githubusercontent.com/204475/71380921-f3926080-2596-11ea-91b9-1f1825bafdc6.jpg)
![20191223151336_1](https://user-images.githubusercontent.com/204475/71380923-f68d5100-2596-11ea-9b12-4245b765e92b.jpg)

Parser also doesn't support [`delete`](https://community.bistudio.com/wiki/raP_File_Format_-_Elite). (I didn't find any other wiki pages for it)

**Comment by X39** [comment]
The commits e149666d93c6310d5828fbef07bf0a49a4915b27, 089b43cb80a1a8a9a6db20e1ea3cb361f34073ac, 461f32acba8abf8d6b0505c7445ffdbb0aceed62 address the required implementation in the parser.

Still todo: Implement the features on backing end

**Comment by X39** [comment]
Fixed on master
